### register
POST http://localhost:8080/api/v1/user/register
Content-Type: application/json

{
  "username": "admin",
  "password": "rahasia"
}

### login
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "username": "admin",
  "password": "rahasia"
}

###
GET http://localhost:8080/api/v1/user/token
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY


###
POST http://localhost:8080/api/v1/category
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI4OH0.QKfyNwd9tgRqTFDyXQZkW_TmlxHQ-a-rkCZhPy1dXs4

{
  "category": "Oil",
  "imageUrl": "https://firebasestorage.googleapis.com/v0/b/tunas-grocery.appspot.com/o/icons%2Fvegetables.png?alt=media&token=6fa1cff3-b573-4165-89ff-864a0bf1553c"
}

### GET CATEGORY BY ID
GET http://localhost:8080/api/v1/category/8c2c184e-11d2-11ec-82a8-0242ac130003
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

### GET CATEGORY
GET https://tunas-grocery.masuk.web.id/category.php
Content-Type: application/json


### GET ALL CATEGORY
GET http://localhost:8080/api/v1/category
Content-Type: application/json

### UPDATE CATEGORY
PUT http://localhost:8080/api/v1/category
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

{
  "id": "8c2c184e-11d2-11ec-82a8-0242ac130003",
  "category": "Fast food",
  "imageUrl": null
}

### DESTROY CATEGORY
DELETE http://localhost:8080/api/v1/category/25bf7094-7d45-11ed-9d53-f45c89b11b13
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY


### PRODUCT
POST http://localhost:8080/api/v1/product
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY


{
  "name": "Carrot",
  "price": 10,
  "weight": 1000,
  "perUnit": 100,
  "description": "Good for health",
  "imageUrl" : null,
  "categoryId": "8c2c184e-11d2-11ec-82a8-0242ac130003"
}

###
PUT http://localhost:8080/api/v1/product
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

{
  "id": "a3c02e8c-11d2-11ec-82a8-0242ac130003",
  "name": "BLACK",
  "price": 10,
  "weight": 1000,
  "perUnit": 100,
  "description": "Good for health",
  "imageUrl" : null,
  "categoryId": "8c2c184e-11d2-11ec-82a8-0242ac130003"
}

### GET ALL PRODUCT
GET http://localhost:8080/api/v1/product
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

### GET TOP PRODUCT
GET http://localhost:8080/api/v1/product/top
Content-Type: application/json

### GET RECOMMENDED PRODUCT
GET http://localhost:8080/api/v1/product/recommended
Content-Type: application/json

### DELETE PRODUCT
DELETE http://localhost:8080/api/v1/product/03d5d220-7d54-11ed-b6e2-f45c89b11b13
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

### PRODUCT BY ID
GET http://localhost:8080/api/v1/product/a3c02e8c-11d2-11ec-82a8-0242ac130003
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

### PRODUCT BY CATEGORY
GET http://localhost:8080/api/v1/product/category/ea8e91dd-2f5f-4eb1-91ae-a5dda6d2a76d

### TOP PRODUCT
POST http://localhost:8080/api/v1/product/top/a3c02e8c-11d2-11ec-82a8-0242ac130003
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

###
GET http://localhost:8080/api/v1/product/top
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

### MAKE TRANSACTION
POST http://localhost:8080/api/v1/transaction
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

{
  "userId": "bf80843e-0dba-4b0c-bcb4-faeaec5e53fa",
  "products": [
    {
      "id": "a3c02e8c-11d2-11ec-82a8-0242ac130003",
      "total": 2
    }
  ]
}

### GET TRANSACTION BY ID
GET http://localhost:8080/api/v1/transaction/de0f77d0-7dcb-11ed-b6b4-f45c89b11b13
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

### GET TRANSACTION BY USER ID
GET http://localhost:8080/api/v1/transaction/user/bf80843e-0dba-4b0c-bcb4-faeaec5e53fa
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

### DESTROY TRANSACTION BY ID
DELETE http://localhost:8080/api/v1/transaction/de0f77d0-7dcb-11ed-b6b4-f45c89b11b13
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

### USER
GET http://localhost:8080/api/v1/user
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

### STORE CART
POST http://localhost:8080/api/v1/cart/bf80843e-0dba-4b0c-bcb4-faeaec5e53fa/a3c02e8c-11d2-11ec-82a8-0242ac130003/2
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

### DESTROY CART
DELETE http://localhost:8080/api/v1/cart/bf80843e-0dba-4b0c-bcb4-faeaec5e53fa/e46cd1f2-7d69-11ed-9bb1-f45c89b11b13
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

### GET USER CART
GET http://localhost:8080/api/v1/cart/bf80843e-0dba-4b0c-bcb4-faeaec5e53fa
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

### ADD WISHLIST
POST http://localhost:8080/api/v1/wishlist/bf80843e-0dba-4b0c-bcb4-faeaec5e53fa/a3c02e8c-11d2-11ec-82a8-0242ac130003
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

### GET USER WISHLIST
GET http://localhost:8080/api/v1/wishlist/bf80843e-0dba-4b0c-bcb4-faeaec5e53fa
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

### DESTROY USER WISHLIST
DELETE http://localhost:8080/api/v1/wishlist/bf80843e-0dba-4b0c-bcb4-faeaec5e53fa/8c934506-7d64-11ed-8570-f45c89b11b13
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY


### get all user
GET http://localhost:8080/api/v1/user/all
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

### grant role to user
POST http://localhost:8080/api/v1/user/role/fc81ccd7-98aa-11ec-ba07-b78370c9a109/5d3337d8-98ab-11ec-ba07-c940688411f4
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

### revote role from user
DELETE http://localhost:8080/api/v1/user/role/1/4
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

### get all roles
GET http://localhost:8080/api/v1/role/all
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

### save role
POST http://localhost:8080/api/v1/role
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

{
  "name" : "USER"
}

### get role by id
GET http://localhost:8080/api/v1/role/4
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY

###
GET http://localhost:8080/api/v1/user/all
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY3MTk0ODI0MX0.vh6eu0fx3a4i1bCPoWGfk714Z98XizAmZDvERipWvJY
