### STORE CATEGORY
POST https://tunas-grocery.herokuapp.com/api/v1/category
Content-Type: application/json

{
  "category": "Fruits",
  "imageUrl": null
}

### Update Category
PUT https://tunas-grocery.herokuapp.com/api/v1/category
Content-Type: application/json

{
  "id": "99f90103-186c-11ec-b6fd-b74e3419320a",
  "category": "Fruits",
  "imageUrl": null
}

### All Category
GET https://tunas-grocery.herokuapp.com/api/v1/category

### Get Category by Id
GET https://tunas-grocery.herokuapp.com/api/v1/category/8c2c184e-11d2-11ec-82a8-0242ac130003

### PRODUCT
### STORE PRODUCT
POST https://tunas-grocery.herokuapp.com/api/v1/product
Content-Type: application/json

{
  "name": "Radish",
  "price": 10,
  "weight": 1000,
  "perUnit": 100,
  "description": "Good for health",
  "category": "8c2c184e-11d2-11ec-82a8-0242ac130003"
}

### UPDATE PRODUCT
PUT https://tunas-grocery.herokuapp.com/api/v1/product
Content-Type: application/json

{
  "name": "Banana",
  "id": "5bebe205-186d-11ec-b6fd-bbc6ac7a7e9f",
  "imageUrl": "https://firebasestorage.googleapis.com/v0/b/tunas-grocery.appspot.com/o/products%2Fbanana.jpg?alt=media&token=aea8a0f7-7ef9-44e2-9662-802f66185be1",
  "price": 10
}

###  GET ALL PRODUCT
GET https://tunas-grocery.herokuapp.com/api/v1/product

### GET PRODUCT BY ID
GET https://tunas-grocery.herokuapp.com/api/v1/product/5bebe205-186d-11ec-b6fd-bbc6ac7a7e9f


### GET PRODUCT BY CATEGORY ID
GET https://tunas-grocery.herokuapp.com/api/v1/product/category/8c2c184e-11d2-11ec-82a8-0242ac130003

### DESTROY PRODUCT ID
DELETE https://tunas-grocery.herokuapp.com/api/v1/product/a3c02e8c-11d2-11ec-82a8-0242ac130003

### TOP PRODUCT
### STORE TOP PRODUCT
POST https://tunas-grocery.herokuapp.com/api/v1/product/top/a3c02e8c-11d2-11ec-82a8-0242ac130003

### GET ALL TOP PRODUCT
GET https://tunas-grocery.herokuapp.com/api/v1/product/top

### RECOMMEDATION PRODUCT
### STORE RECOMMEDATION PRODUCT
POST https://tunas-grocery.herokuapp.com/api/v1/product/recommendation/5bebe205-186d-11ec-b6fd-bbc6ac7a7e9f

### GET ALL RECOMMEDATION PRODUCT
GET https://tunas-grocery.herokuapp.com/api/v1/product/recommendation

### TRANSACTION
POST https://tunas-grocery.herokuapp.com/api/v1/transaction
Content-Type: application/json

{
  "userId":"ac723ce6-11d2-11ec-82a8-0242ac130003",
  "products": [
    {"id": "d7c6d7a4-186c-11ec-b6fd-23e8ea136663", "name": "Carrot", "price": 10, "weight": 1000, "perUnit": 100, "total": 2}
  ]
}


### GET CUSTOMER TRANSACTION
GET https://tunas-grocery.herokuapp.com/api/v1/transaction/customer/ac723ce6-11d2-11ec-82a8-0242ac130003

### DELETE CUSTOMER TRANSACTION
DELETE https://tunas-grocery.herokuapp.com/api/v1/transaction/b25bfd97-3007-11ec-8d6b-a9270818bed5

### CUSTOMER
GET https://tunas-grocery.herokuapp.com/api/v1/customer

### STORE CART
POST https://tunas-grocery.herokuapp.com/api/v1/cart/ac723ce6-11d2-11ec-82a8-0242ac130003/d7c6d7a4-186c-11ec-b6fd-23e8ea136663/2

### DESTROY CART
DELETE https://tunas-grocery.herokuapp.com/api/v1/cart/ac723ce6-11d2-11ec-82a8-0242ac130003/7866b1e5-187c-11ec-9e94-e9fbbd5e8748

### GET CUSTOMER CART
GET https://tunas-grocery.herokuapp.com/api/v1/cart/ac723ce6-11d2-11ec-82a8-0242ac130003

### STORE WISHLIST
POST https://tunas-grocery.herokuapp.com/api/v1/wishlist/ac723ce6-11d2-11ec-82a8-0242ac130003/d7c6d7a4-186c-11ec-b6fd-23e8ea136663

### GET WISHLIST
GET https://tunas-grocery.herokuapp.com/api/v1/wishlist/ac723ce6-11d2-11ec-82a8-0242ac130003/d7c6d7a4-186c-11ec-b6fd-23e8ea136663

### DESTROY WISHLIST
DELETE https://tunas-grocery.herokuapp.com/api/v1/wishlist/ac723ce6-11d2-11ec-82a8-0242ac130003/d7c6d7a4-186c-11ec-b6fd-23e8ea136663

### GET CUSTOMER WISHLIST
GET https://tunas-grocery.herokuapp.com/api/v1/wishlist/ac723ce6-11d2-11ec-82a8-0242ac130003
